version: 2

jobs:
  test:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/chroju/tfdoc
    steps:
      - checkout
      - restore_cache:
          keys:
            - vendor
      - run: go get github.com/golang/dep/cmd/dep
      - run: go get golang.org/x/tools/cmd/cover
      - run: go get github.com/mattn/goveralls
      - run: dep ensure -v
      - save_cache:
          key: vendor-{{ checksum "Gopkg.lock" }}
          paths:
            - ${CIRCLE_WORKING_DIRECTORY}/vendor
      - run: go test -v -covermode=count -coverprofile=coverage.out ./scraping
      - run: goveralls -coverprofile=coverage.out -service=circle-ci -repotoken $COVERALLS_REPO_TOKEN
      - save_cache:
          key: source-{{ epoch }}
          paths:
            - ${CIRCLE_WORKING_DIRECTORY}
  deploy:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/chroju/tfdoc
    steps:
      - restore_cache:
          keys:
            - source
      - run: go get github.com/mitchellh/gox
      - run: go get github.com/tcnksm/ghr
      - run: gox -os="linux windows" -arch="386 amd64" -output "bin/{{.OS}}_{{.Arch}}/{{.Dir}}"
      - run: ${CIRCLE_WORKING_DIRECTORY}/.circleci/compress_binaries.sh
      - run: ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME $CIRCLE_TAG pkg/

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - deploy:
          filters:
            tags:
              only: /^v.*$/
            branches:
              ignore: /.*/
